### ISSUE TITLE
Sort Tracks in „Your Feed“ with newest uploads first / with GPS Data

### ISSUE THREAD

**Issue by rotger711** [openbikesensor/obsApp#14]
It would be good to always have the newest uploaded tracks o the first page. actually this is given under „global Feed“. Under „Your Feed“ the newest tracks are on the last page. This makes it complicated to edit as soon as you have many track uploads (including those without any gps Data because the OBS was just switched on and off).
In the same go way it could be helpful to show only tracks with real GPS content / delete all tracks without GPS Data in one go? - Reinhard Otter

**Comment by opatut** [comment]
Solved in openbikesensor/obsAPI@f5bb11e0a08e3da6c55fcb6ca619fc17a19991b2 which is part of openbikesensor/obsAPI#26.
