### ISSUE TITLE
Ungültige GPX-Dateien

### ISSUE THREAD

**Issue by Natenom** [openbikesensor/obsApp#17]
Wenn man csv-Daten als GPX exportiert und wenn in den Daten anfangs keine Geokoordinaten drin waren, dann sieht ein Trackpoint so aus:

```
<trkpt  lat="null" lon="null">
<name>3</name>
<cmt> d1="null" d2="null" </cmt>
</trkpt>
```
Das ergibt einen Fehler z. B. in GPXSee:
```
Error loading data file:
/home/tmp/track.gpx
Invalid longitude
Line: 5
```

Vielleicht könnte man die Zeilen ohne GPS-Koordinaten einfach wegfiltern? Wenn ich diese Zeilen manuell entferne, kann die Datei geöffnet werden.

**Comment by mega-stoffel** [comment]
ich vermute, dass es nicht an fehlenden GPS-Koordinaten liegt, sondern daran, dass Du in Deiner Privacy-Zone warst und daher absichtlich keine GPS-Ortsangaben eingetragen sind.
Aber ich pflichte bei: ich fände es auch besser, die NULL-Daten gar nicht erst auszugeben.
Kann das sein?
