### ISSUE TITLE
GPS Track not "Strava compliant"

### ISSUE THREAD

**Issue by mega-stoffel** [openbikesensor/obsApp#25]
I downloaded an OBS track and wanted to upload it to my cycling history in Strava. This was necessary, because I forgot to record it on my phone.
But such a track is not compliant to the Strava website, because it's missing the time information. See here:
--> https://support.strava.com/hc/en-us/articles/216917947-Uploading-GPS-files-without-time-information
Tracks without time information are more likely considered as "routes", whereas tracks including such time information could be used for the personal records. Maybe we could offer both options, if it's not hard to implement?

**Comment by opatut** [comment]
Thanks for your report. I've created a new ticket at obsAPI#27 to track proper generation of various output formats. I've linked this issue for reference as well. In the server-side implementation we'll make sure to build it in a way that is strava compatible ;)
