### ISSUE TITLE
Show creation date of uploaded tracks instead of upload date

### ISSUE THREAD

**Issue by groma84** [openbikesensor/obsApp#4]
At the moment we show the date of upload when viewing/listing tracks on the website.

It should list the creation date of the track itself instead.

**Comment by uwewoessner** [comment]
If someone wants to jump in and fix it:
We should separate all metadata from the actual track information.
A device ID would be fine in addition to the user ID
The sensor position and width of the handle bar,  should also be part of the metadata set for each track.
A work around for your issue would be to just display the date of the first trackpoint.

**Comment by groma84** [comment]
Is there a documentation of the track format somewhere, or is it "self-explanatory" anyway?

**Comment by opatut** [comment]
![image](https://user-images.githubusercontent.com/235784/105040254-e5e13000-5a61-11eb-8b2b-60a0e2f93be1.png)

This has been implemented already. When the API publishes this information (it does in master already), the frontend will also show it.
